package com.grupo5e.morapack.core.enums;

public enum EstadoVuelo {
    DISPONIBLE, //VUELO LISTO PARA ASIGNAR PEDIDOS
    CANCELADO, //VUELO CANCELADO POR ARCHIVO DE CANCELACIONES
    EN_VUELO //VUELO QUE YA PARTIO PERO NO LLEGO
}
